##  Laboratorio 5 : Soluciones

## Problema 1

Dado un arreglo aleatorio de enteros (debe crearlo con sample) hallar el subarreglo con máxima suma posible de este y encontrar su subsecuencia creciente más larga y además la cantidad de secuencias diferentes que puede generar módulo $10^{9}+7$. Tome como referencia el siguiente arreglo:  
  
$$ A = \{95 ,-43, -59, 10, -80, 20, -92, 75, 61, -50\} $$

### Solución:


In [37]:
#Definimos un arreglo de prueba
A <- c(95,-43,-59,10,-80,20,-92,75,61,-50)

#S guarda la suma acumulada de los elementos del arreglo
S <- cumsum(A)

#l y r guardaran los limites del subarreglo con mayor suma posible
l <- -1
r <- -1
maximo <- -Inf

#Se analizan todas las posibles sumas de los subarreglos y se obtiene el maximo
for (i in 1:length(A)){
    for (j in i:length(A)){
        suma <- S[j]
        if(i > 1) suma <- suma - S[i-1]
        if(maximo < suma){
            l <- i
            r <- j
            maximo <- suma
        }
    }
}

cat("La suma maxima es ",maximo,", y se consigue con el subarreglo de tamaño ",r-l+1 ,"con indice inicial ",l," e indice final ",
    r,"\n")
Subarreglo<-A[l:r]
cat("El subarreglo en cuestion es: ",Subarreglo)

La suma maxima es  136 , y se consigue con el subarreglo de tamaño  2 con indice inicial  8  e indice final  9 
El subarreglo en cuestion es:  75 61

In [38]:
#indice_incio e indice_fin guardaran los indices de las subsecuencias en orden creciente
indice_inicio<-NULL
indice_fin<-NULL
indice_inicio[1]<-1
indice_fin[1]<-1
#size guardara los tamaños de las subsecuencias en orden creciente
size<-NULL
#Inicializamos a 1
size[1]<-1
#maxlen guardara la maxima longitud que se haya encontrado de una subsecuencia creciente
maxlen<-1
#subsecuencia_mas_grande nos dira cual subsecuencia de las encontradas es la de mayor longitud
subsecuencia_mas_grande<-1
#x representa el # de subsecuencia que se esta analizando
x<-1
#Empezamos analizando elementos del Subarreglo empezando del 2do elemento
if(length(Subarreglo)>1){
for(i in 2:length(Subarreglo)){
        #Verificamos si el elemento es mayor que el anterior, en caso positivo el elemento se toma como parte de la subsecuencia
        #creciente, en caso contrario dicho elemento se toma como el ultimo de la subsecuencia analizada y se comienza a analizar
        #una subsecuencia diferente en caso de que queden mas elementos.
        if(Subarreglo[i] > Subarreglo[i-1]){
            indice_fin[x]<-i
            size[x]<-size[x]+1
            #En caso la subsecuencia actualmente analizada tenga mayor longitud que el maximo actual, dicha subsecuencia se tomara
            #como la nueva subsecuencia de mayor longitud
            if(size[x]>=maxlen){
                  maxlen<-size[x]
                  subsecuencia_mas_grande<-x
                }
        }
        else{
            x<-x+1
            indice_inicio[x]<-i
            indice_fin[x]<-i
            size[x]<-1
        }
    }
}

#Luego de analizar todos los elementos mostramos la subsecuencia creciente con mayor longitud
cat("La subsecuencia con mayor longitud es: ",Subarreglo[indice_inicio[subsecuencia_mas_grande]:indice_fin[subsecuencia_mas_grande]],
   "y posee una longitud de: ",size[subsecuencia_mas_grande])


La subsecuencia con mayor longitud es:  75 y posee una longitud de:  1

In [39]:
#La cantidad de posibles subsecuencias diferentes se calcula de la siguiente manera:
length(Subarreglo)*(length(Subarreglo)+1)/2 +1

[1] 4

## Problema 2

Asuma que tiene un diccionario de palabras de máxima longitud 6 y además compuestas solamente por letras minúsculas de la a a la j. Determine la letra que se repita más veces dentro de este conjunto.  
  
Tome como referencia la siguiente función, la cual devuelve el valor ASCII de un caracter.
&nbsp;  

&emsp;&emsp; `asc <- function(x) { strtoi(charToRaw(x),16L) }`  
  
Además para leer el archivo input_p2.txt se usa el siguiente comando:  
  
&emsp;&emsp;`X <- read.table("input_p2.txt",sep=" ")`  
&emsp;&emsp;`X <- X[!is.na(X)]`  
  
Descárguelo del siguiente link: [Input](https://github.com/racsosabe/Estadistica-2017-II/blob/master/input_p2.txt)  

### Solución:


In [9]:
#Definimos la función que devuelve el codigo ASCII de una letra
asc <- function(x) { strtoi(charToRaw(x),16L) }
#Probamos dicha función con una palabra y notamos que nos devuelve el codigo ASCII de cada letra que conforma la palabra
asc("prueba")

[1] 112 114 117 101  98  97

In [12]:
#Guardamos el input a analizar en la variable X
X <- read.table("input_p2.txt",sep=" ")
#Quitamos los elementos NA
X <- X[!is.na(X)]
#Verificamos su contenido
X

[1] "bb"     "haj"    "hicg"   "ibi"    "ghhjda" "gej"    "jfa"    "jcdiec"
 [9] "bda"    "hi"     "ifg"    "ci"     "c"      "e"      "dbiidf" "hjibde"
[17] "ge"     "g"      "dej"    "jbhjgb" "de"     "ddabe"  "cejfie" "egaaj" 
[25] "j"      "fdaejc" "eg"     "hbaig"  "aaiibe" "hbeic"  "h"      "hc"    
[33] "d"      "iefe"   "fic"    "ecig"   "g"      "hajagh" "igi"    "jecccg"
[41] "ibf"    "fac"    "ibcgaj" "j"      "gidg"

In [100]:
#Definimos un contador para los 10 letras diferentes (a-j)
contador<-replicate(10,0)
contador

[1] 0 0 0 0 0 0 0 0 0 0

In [101]:
#Analizamos palabra por palabra
for(palabra in X){
    #Hacemos la correspondecia 'a'=1,'b'=2,... restando el valor de asc('a') y sumando el valor de 1, para motivos prácticos
    t<-asc(palabra)-asc('a')+1
    #t guarda el vector de indices correspondientes al contador al cual se le deben adicionar 1
    for(i in t)
    contador[i]<-contador[i]+1
}

#Verificamos el contador
contador


[1] 15 14 16 13 19  9 18 13 23 17

In [109]:
#Identificamos el indice con mayor valor. Si usamos which.max() solo nos dara el indice del 1er valor máximo que encuentre.
posicion<-which(contador == max(contador) )
posicion

[1] 9

In [113]:
#Traducimos dicha posición a la letra correspondiente
cat("La letra que se repite más veces es: ",letters[posicion])

La letra que se repite más veces es:  i

## Problema 3

Halle el $n$-ésimo término de Fibonacci usando matrices. Pruebe para $n = 25$

### Solución:

$$ F_{i} = F_{i-1} + F_{i-2} $$  
$$ F_{0}=0 $$  
$$ F_{1}=1 $$  
Aplicamos la siguiente fórmula para hallar el termino `n`
$$ \begin{pmatrix} F_{n+1} \\ F_{n} \end{pmatrix} = \begin{pmatrix} 1 &1 \\\\ 1 &0 \end{pmatrix}^{n}\begin{pmatrix}F_{1} \\ F_{0} \end{pmatrix} $$

In [154]:

# Secuencia de Fibonacci: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181,6765, 10946, 17711, 
# 28657, 46368, 75025 (termino 25)

#Definimos n para el termino que queremos hallar
n <- 25
#Definimos la matriz principal
coeficientes <- c(1,1,1,0)
M <- matrix(coeficientes,nrow=2,byrow=T)
M

[,1] [,2]
[1,]    1    1
[2,]    1    0

In [159]:
#N guardara el resultado de las multiplicaciones de M consigo misma
N <- M
#Definimos el vector correspondiente a (F1 F0)
F <- c(1,0)

#Multiplicamos M consigo misma (n-1) veces consecutivas para obtener M^n
i<-1
while(i<n){
    N <- N %*% M
    i<-i+1
}
#Finalmente multiplicamos M^n por (F1 F0)
F <- N %*% F
#El 2do termino del resultado nos mostrara el valor del n-esimo termino de la sucesion de Fibonacci
print(F[2])



[1] 75025


## Problema 4

Suponga que la matriz de adyacencia de un grafo es la siguiente:  
$$ Adj = \begin{pmatrix} 0 &1 &1 &0 \\ 1 &0 &0 &0 \\ 1&1 &0 &0 \\ 0 &0 &1 &0 \end{pmatrix} $$

Si quisieramos tener la cantidad de caminos de dos a dos nodos de longitud $k$ en otra matriz M, determine de qué nodo $u$ a qué nodo $v$ se puede obtener la mayor cantidad de estos caminos.  
Pruebe para $k=10$.

### Solución:

Calculamos M de la siguiente manera:  
$$M=Adj^n$$

In [219]:
#La matriz Caminos representa la cantidad de caminos de longitud k de un nodo u a un nodo v
#Inicializamos con la matriz Identidad de tamaño 4
Caminos<-diag(4)
Caminos

[,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

In [220]:
#k representa la longitud de los caminos
k <- 10
#Creamos la matriz de Adyacencia
data <- c(0,1,1,0,1,0,0,0,1,1,0,0,0,0,1,0)
Adj <- matrix(data,nrow=4,byrow=T)
Adj

[,1] [,2] [,3] [,4]
[1,]    0    1    1    0
[2,]    1    0    0    0
[3,]    1    1    0    0
[4,]    0    0    1    0

In [221]:
#Multiplicamos la matriz de adyacencia consigo misma k veces
i<-1
while(i<=k){
    Caminos <- Caminos %*% Adj
    i <- i+1
}

Caminos

[,1] [,2] [,3] [,4]
[1,]   56   55   33    0
[2,]   33   34   22    0
[3,]   55   55   34    0
[4,]   34   34   21    0

In [222]:
#Obtenemos el indice del valor máximo de la matriz
indice<-which.max(Caminos)
#Mostramos el numero maximo de caminos de longitud k
Caminos[indice]

[1] 56

In [238]:
#Obtenemos los nodos u y v que contienen la maxima cantidad de caminos
which(Caminos==max(Caminos),arr.ind=TRUE)
u<-which(Caminos==max(Caminos),arr.ind=TRUE)[1]
v<-which(Caminos==max(Caminos),arr.ind=TRUE)[2]
cat("La mayor cantidad de caminos se obtiene desde el nodo ",u,"hacia el nodo ",v)

row col
[1,]   1   1

La mayor cantidad de caminos se obtiene desde el nodo  1 hacia el nodo  1